### ISSUE TITLE
Add More JavaScript Questions

### ISSUE THREAD

**Issue by Abhay0809** [Abhay0809/JavaScript-Program#3]
- Update Readme
- Add Question at top

**Comment by abhijeetekad** [comment]
Added question number 8 please check

**Comment by Abhay0809** [comment]
> Added question number 8 please check

Update Readme too

**Comment by karan-2028** [comment]
i would like to contribute over this.
can you please assign me .

**Comment by sumanchaurasiya** [comment]
I would like to contribute.

**Comment by namratanimmi** [comment]
I would like to contribute , please assign me this.

**Comment by skinnyiam** [comment]
I would like to add problems and contribute , can you please assign me this

**Comment by 8228069354** [comment]
i would like to contribute please assign this.
